#ifndef _INTERACTIVE_FLUIDSYSTEMINTERFACE_SHADERS_CONSTANT_HLSL
#define _INTERACTIVE_FLUIDSYSTEMINTERFACE_SHADERS_CONSTANT_HLSL

static const float4x4 IDENTITY = float4x4 (1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1);
static const float PI = 3.141592653f;

#endif /* _INTERACTIVE_FLUIDSYSTEMINTERFACE_SHADERS_CONSTANT_HLSL */
