#pragma kernel RandomParticle

#include "DefaultParticle.hlsl"
#include "Tools.hlsl"

RWStructuredBuffer<Particle> _Buffer;
uint _BufferCount;

float4x4 _SimSpaceLocalToWorld;

[numthreads(128,1,1)]
void RandomParticle(uint3 id : SV_DispatchThreadID)
{
    const uint pid= id.x;
    if(pid >= _BufferCount) return;

    Particle p = _Buffer[pid];
    p.pos = GenerateRandomPos(pid, _SimSpaceLocalToWorld);
    _Buffer[pid] = p;
}